### ISSUE TITLE
Should node use nearest parent .node-version file?

### ISSUE THREAD

**Issue by will-stone** [fisherman/verman#2]
I've put 8.6.0 in `~/.node-version`, and 

```
# auto switch node versions based on .node-version file
function node -d "Server-side JavaScript runtime"
    verman "node"
    command node $argv
end
```

in my `~/.config/fish/functions/node.fish` file, so that node versions are automatically picked up. Navigating to `~` does indeed select 8.6.0 but if I travel to any other folder below, then node falls back to the installed version, which for me is currently 8.5.0. Is this as intended? Or have I set up my config incorrectly?

**Comment by jorgebucaran** [comment]
>  Is this as intended?

Yes. I was mimicking what I think/thought nvm did at the time and I've found it to be exactly what I need. My reasoning is that I would only need that version of node inside that directory.

What do you think?

**Comment by will-stone** [comment]
Oh ok. It's not how nvm works (I'm coming from zsh + nvm); nvm will go up and find the nearest parent version. I'd personally prefer that but it's totally up to you. I've just found out that both this and fnm don't have this feature. Probably not enough to have me running back to zsh though 🙂

**Comment by JorgeBucaran** [comment]
@will-stone In that case my understanding of nvm was wrong! 😅  

I am open to introduce this feature if you would like to implement it though. I would be happy to answer any questions you have about fishshell script as well. 

But honestly, I haven't found myself in a place where I thought I'd need something like this though.

**Comment by will-stone** [comment]
Crikey, not sure I've got the cojones for shell scripting yet. I may come back in the future though. As this is obviously working as you intended, I'll mark this as closed. Thanks.

**Comment by JorgeBucaran** [comment]
@will-stone If you need help with anything just let me know.

Check out https://github.com/JorgeBucaran/fish-shell-cookbook if you have time for that too. 

Cheers!
